# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Procedure Agents Dataset-neuro
#'
#' A SDTM AG dataset recording details of agents such as a PET tracer used in procedures
#'
#' @name ag_neuro
#' @title Procedure Agents Dataset-neuro
#' @keywords dataset
#' @description A SDTM AG dataset recording details of agents such as a PET tracer used in procedures
#' @docType data
#' @format A data frame with 13 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{AGSEQ}{Sequence Number}
#'     \item{AGTRT}{Reported Agent Name}
#'     \item{AGCAT}{Category for Agent}
#'     \item{AGDOSE}{Dose per Administration}
#'     \item{AGDOSEU}{Dose Units}
#'     \item{AGROUTE}{Route of Administration}
#'     \item{AGLNKID}{Link ID}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{AGSTDTC}{Start Date/Time of Agent}
#'   }
#'
#' @source Constructed by admiralneuro developers
"ag_neuro"
