# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Biospecimen Events
#'
#' A synthetic SDTM BE domain representing specimen collection, aliquoting, and culturing events, with linkage to MB and MS domains
#'
#' @name be
#' @title Biospecimen Events
#' @keywords dataset microbiology
#' @description A synthetic SDTM BE domain representing specimen collection, aliquoting, and culturing events, with linkage to MB and MS domains
#' @docType data
#' @format A data frame with 13 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{BESEQ}{Sequence Number}
#'     \item{BEREFID}{Reference ID}
#'     \item{BELNKID}{Link Identifier}
#'     \item{BETERM}{Reported Term for the Biospecimen Event}
#'     \item{BECAT}{Category for Biospecimen Event}
#'     \item{BELOC}{Anatomical Location of Event}
#'     \item{VISITNUM}{Visit Number}
#'     \item{BEDTC}{Date/Time of Specimen Collection}
#'     \item{BESTDTC}{Start Date/Time of Biospecimen Event}
#'     \item{BEENDTC}{End Date/Time of Biospecimen Event}
#'   }
#'
#' @source [Access the source of the Biospecimen Events dataset.](https://github.com/pharmaverse/pharmaversesdtm/blob/main/data/be.rda)
"be"
