# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Demographic Dataset-neuro
#'
#' A SDTM DM dataset for Alzheimer's disease studies
#'
#' @name dm_neuro
#' @title Demographic Dataset-neuro
#' @keywords dataset neurology
#' @description A SDTM DM dataset for Alzheimer's disease studies
#' @docType data
#' @format A data frame with 26 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{SUBJID}{Subject Identifier for the Study}
#'     \item{RFSTDTC}{Subject Reference Start Date/Time}
#'     \item{RFENDTC}{Subject Reference End Date/Time}
#'     \item{RFXSTDTC}{Date/Time of First Study Treatment}
#'     \item{RFXENDTC}{Date/Time of Last Study Treatment}
#'     \item{RFICDTC}{Date/Time of Informed Consent}
#'     \item{RFPENDTC}{Date/Time of End of Participation}
#'     \item{DTHDTC}{Date/Time of Death}
#'     \item{DTHFL}{Subject Death Flag}
#'     \item{SITEID}{Study Site Identifier}
#'     \item{AGE}{Age}
#'     \item{BRTHDTC}{Date/Time of Birth}
#'     \item{AGEU}{Age Units}
#'     \item{SEX}{Sex}
#'     \item{RACE}{Race}
#'     \item{ETHNIC}{Ethnicity}
#'     \item{ARMCD}{Planned Arm Code}
#'     \item{ARM}{Description of Planned Arm}
#'     \item{ACTARMCD}{Actual Arm Code}
#'     \item{ACTARM}{Description of Actual Arm}
#'     \item{COUNTRY}{Country}
#'     \item{DMDTC}{Date/Time of Collection}
#'     \item{DMDY}{Study Day of Collection}
#'     \item{ARMNRS}{Reason Arm and/or Actual Arm is Null}
#'   }
#'
#' @source Constructed by {admiralneuro} developers
"dm_neuro"
