# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Immunogenicity Specimen Assessments for ADA
#'
#' A SDTM IS dataset containing relevant antidrug antibody assessment studies
#'
#' @name is_ada
#' @title Immunogenicity Specimen Assessments for ADA
#' @keywords dataset
#' @description A SDTM IS dataset containing relevant antidrug antibody assessment studies
#' @docType data
#' @format A data frame with 22 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{ISSEQ}{Sequence Number}
#'     \item{ISTESTCD}{Immunogenicity Test/Exam Short Name}
#'     \item{ISTEST}{Immunogenicity Test or Examination Name}
#'     \item{ISBDAGNT}{Binding Agent}
#'     \item{VISIT}{Visit Name}
#'     \item{ISORRES}{Result or Finding in Original Units}
#'     \item{ISORRESU}{Original Units}
#'     \item{ISSTRESC}{Character Result/Finding in Std Format}
#'     \item{ISSTRESN}{Numeric Results/Findings in Std. Units}
#'     \item{ISSTRESU}{Standard Units}
#'     \item{ISNAM}{Vendor Name}
#'     \item{ISSPEC}{Specimen Type}
#'     \item{ISLLOQ}{Lower Limit of Quantitation}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISITDY}{Planned Study Day of Visit}
#'     \item{ISDTC}{Date/Time of Specimen Collection}
#'     \item{ISDY}{Actual Study Day of Specimen Collection}
#'     \item{ISTPT}{Planned Time Point Name}
#'     \item{ISTPTNUM}{Planned Time Point Number}
#'   }
#'
#' @source Generated dataset
#' @author Kristin Dahnert
#' @details Contains a set of 2 unique Test Short Names and Test Names: \tabular{ll}{
#'   \strong{ISTESTCD} \tab \strong{ISTEST} \cr
#'   ADA_BAB \tab Binding Antidrug Antibody             \cr
#'   ADA_NAB \tab Neutralizing Binding Antidrug Antibody
#' }

"is_ada"
