# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Laboratory Measurements Dataset-metabolic
#'
#' A SDTM LB dataset containing relevant laboratory measurements for metabolic studies
#'
#' @name lb_metabolic
#' @title Laboratory Measurements Dataset-metabolic
#' @keywords dataset
#' @description A SDTM LB dataset containing relevant laboratory measurements for metabolic studies
#' @docType data
#' @format A data frame with 23 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{LBSEQ}{Sequence Number}
#'     \item{LBTESTCD}{Lab Test or Examination Short Name}
#'     \item{LBTEST}{Lab Test or Examination Name}
#'     \item{LBCAT}{Category for Lab Test}
#'     \item{LBORRES}{Result or Finding in Original Units}
#'     \item{LBORRESU}{Original Units}
#'     \item{LBORNRLO}{Reference Range Lower Limit in Orig Unit}
#'     \item{LBORNRHI}{Reference Range Upper Limit in Orig Unit}
#'     \item{LBSTRESC}{Character Result/Finding in Std Format}
#'     \item{LBSTRESN}{Numeric Result/Finding in Standard Units}
#'     \item{LBSTRESU}{Standard Units}
#'     \item{LBSTNRLO}{Reference Range Lower Limit-Std Units}
#'     \item{LBSTNRHI}{Reference Range Upper Limit-Std Units}
#'     \item{LBNRIND}{Reference Range Indicator}
#'     \item{LBBLFL}{Baseline Flag}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{VISITDY}{Planned Study Day of Visit}
#'     \item{LBDTC}{Date/Time of Specimen Collection}
#'     \item{LBDY}{Study Day of Specimen Collection}
#'   }
#'
#' @source Constructed by {admiralmetabolic} developers
#' @details Contains a list of 9 unique Test Short Names (LBTESTCD) and Test Names (LBTEST):
#'   \describe{
#'     \item{ALB}{Albumin}
#'     \item{ALP}{Alkaline Phosphatase}
#'     \item{AST}{Aspartate Aminotransferase}
#'     \item{CHOL}{Cholesterol}
#'     \item{GGT}{Gamma Glutamyl Transferase}
#'     \item{GLUC}{Glucose}
#'     \item{HBA1CHGB}{Hemoglobin A1C/Hemoglobin}
#'     \item{INSULIN}{Insulin}
#'     \item{TRIG}{Triglycerides}
#'   }
#'
"lb_metabolic"
