# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Laboratory Test Dataset-neuro
#'
#' A SDTM LB domain dataset containing laboratory test results for Alzheimer's Disease studies
#'
#' @name lb_neuro
#' @title Laboratory Test Dataset-neuro
#' @keywords dataset neurology
#' @description A SDTM LB domain dataset containing laboratory test results for Alzheimer's Disease studies
#' @docType data
#' @format A data frame with 23 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{LBSEQ}{Sequence Number}
#'     \item{LBTESTCD}{Lab Test or Examination Short Name}
#'     \item{LBTEST}{Lab Test or Examination Name}
#'     \item{LBCAT}{Category for Lab Test}
#'     \item{LBORRES}{Result or Finding in Original Units}
#'     \item{LBORRESU}{Original Units}
#'     \item{LBORNRLO}{Reference Range Lower Limit in Orig Unit}
#'     \item{LBORNRHI}{Reference Range Upper Limit in Orig Unit}
#'     \item{LBSTRESC}{Character Result/Finding in Std Format}
#'     \item{LBSTRESN}{Numeric Result/Finding in Standard Units}
#'     \item{LBSTRESU}{Standard Units}
#'     \item{LBSTNRLO}{Reference Range Lower Limit-Std Units}
#'     \item{LBSTNRHI}{Reference Range Upper Limit-Std Units}
#'     \item{LBNRIND}{Reference Range Indicator}
#'     \item{LBBLFL}{Baseline Flag}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{VISITDY}{Planned Study Day of Visit}
#'     \item{LBDTC}{Date/Time of Specimen Collection}
#'     \item{LBDY}{Study Day of Specimen Collection}
#'   }
#'
#' @source Constructed by {admiralneuro} developers
#' @details Contains a set of 2 unique Test Short Names and Test Names: \tabular{ll}{
#'   \strong{LBTESTCD} \tab \strong{LBTEST} \cr
#'   ASYNASAA \tab Alpha Synuclein Seed Amplification Assay (CSF)     \cr
#'   PTAB42R  \tab Lumipulse G pTau 217/Beta-Amyloid 1-42 Plasma Ratio
#' }

"lb_neuro"
