# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Laboratory Measurements (PSA) for Oncology
#'
#' A SDTM LB dataset for prostate cancer studies intended for examples of ADaM dataset creation
#'
#' @name lb_onco_pcwg
#' @title Laboratory Measurements (PSA) for Oncology
#' @keywords dataset
#' @description A SDTM LB dataset for prostate cancer studies intended for examples of ADaM dataset creation
#' @docType data
#' @format A data frame with 18 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{LBSEQ}{Sequence Number}
#'     \item{LBTESTCD}{Lab Test or Examination Short Name}
#'     \item{LBTEST}{Lab Test or Examination Name}
#'     \item{LBCAT}{Category for Lab Test}
#'     \item{LBORRES}{Result or Finding in Original Units}
#'     \item{LBORRESU}{Original Units}
#'     \item{LBSTRESC}{Character Result/Finding in Std Format}
#'     \item{LBSTRESN}{Numeric Result/Finding in Standard Units}
#'     \item{LBSTRESU}{Standard Units}
#'     \item{LBBLFL}{Baseline Flag}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{VISITDY}{Planned Study Day of Visit}
#'     \item{LBDTC}{Date/Time of Specimen Collection}
#'     \item{LBDY}{Study Day of Specimen Collection}
#'   }
#'
#' @source Generated dataset
#' @author Tomoyuki Namai
#' @details Contains a set of 1 unique Test Short Name and Test Name: \tabular{ll}{
#'   \strong{LBTESTCD} \tab \strong{LBTEST} \cr
#'   PSA \tab Prostate Specific Antigen
#' }

"lb_onco_pcwg"
