# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Neurological Assessment Dataset-neuro
#'
#' A SDTM NV dataset containing neurological assessments or test results
#'
#' @name nv_neuro
#' @title Neurological Assessment Dataset-neuro
#' @keywords dataset neurology
#' @description A SDTM NV dataset containing neurological assessments or test results
#' @docType data
#' @format A data frame with 21 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{NVSEQ}{Sequence Number}
#'     \item{NVLNKID}{Link ID}
#'     \item{NVTESTCD}{Short Name of Nervous System Test}
#'     \item{NVTEST}{Name of Nervous System Test}
#'     \item{NVCAT}{Category for Nervous System Test}
#'     \item{NVLOC}{Location Used for the Measurement}
#'     \item{NVMETHOD}{Method of Test or Examination}
#'     \item{NVNAM}{Vendor Name}
#'     \item{NVORRES}{Result or Finding in Original Units}
#'     \item{NVORRESU}{Original Units}
#'     \item{NVSTRESC}{Character Result/Finding in Std Format}
#'     \item{NVSTRESN}{Numeric Result/Finding in Standard Units}
#'     \item{NVSTRESU}{Standard Units}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{NVDTC}{Date/Time of Collection}
#'     \item{NVDY}{Study Day of Collection}
#'     \item{NVLOBXFL}{Last Observation Before Exposure Flag}
#'   }
#'
#' @source Constructed by {admiralneuro} developers
#' @details Contains a set of 3 unique Test Short Names and Test Names: \tabular{ll}{
#'   \strong{NVTESTCD} \tab \strong{NVTEST} \cr
#'   SUVR  \tab Standardized Uptake Value Ratio                     \cr
#'   UPSIT \tab University of Pennsylvania Smell Identification Test\cr
#'   VR    \tab Qualitative Visual Classification
#' }

"nv_neuro"
