# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Pharmacokinetic Parameters
#'
#' A SDTM PP dataset simulated by Antonio Rodriguez Contesti
#'
#' @name pp
#' @title Pharmacokinetic Parameters
#' @keywords dataset
#' @description A SDTM PP dataset simulated by Antonio Rodriguez Contesti
#' @docType data
#' @format A data frame with 14 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{PPSEQ}{Sequence Number}
#'     \item{PPTESTCD}{Parameter Short Name}
#'     \item{PPTEST}{Parameter Name}
#'     \item{PPCAT}{Parameter Category}
#'     \item{PPORRES}{Result or Finding in Original Units}
#'     \item{PPORRESU}{Original Units}
#'     \item{PPSTRESC}{Character Result/Finding in Std Format}
#'     \item{PPSTRESN}{Numeric Result/Finding in Standard Units}
#'     \item{PPSTRESU}{Standard Units}
#'     \item{PPSPEC}{Specimen Material Type}
#'     \item{PPRFDTC}{Date/Time of Reference Point}
#'   }
#'
#' @source [Access the source of the Pharmacokinetic Parameters dataset.](https://github.com/pharmaverse/pharmaversesdtm/blob/main/data/pp.rda)
#' @author Antonio Rodriguez Contesti
#' @details Contains a set of 10 unique Test Short Names and Test Names: \tabular{ll}{
#'   \strong{PPTESTCD} \tab \strong{PPTEST} \cr
#'   AUCALL  \tab AUC All                      \cr
#'   AUCLST  \tab AUC to Last Nonzero Conc     \cr
#'   CLST    \tab Last Nonzero Conc            \cr
#'   CMAX    \tab Max Conc                     \cr
#'   LAMZ    \tab Lambda z                     \cr
#'   LAMZHL  \tab Half-Life Lambda z           \cr
#'   LAMZNPT \tab Number of Points for Lambda z\cr
#'   RCAMINT \tab Ae                           \cr
#'   RENALCL \tab CLR                          \cr
#'   TMAX    \tab Time of CMAX
#' }

"pp"
