# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Questionnaire for Ophthalmology
#'
#' An example Questionnaires SDTM dataset with ophthalmology-specific questionnaire of NEI VFQ-25
#'
#' @name qs_ophtha
#' @title Questionnaire for Ophthalmology
#' @keywords dataset
#' @description An example Questionnaires SDTM dataset with ophthalmology-specific questionnaire of NEI VFQ-25
#' @docType data
#' @format A data frame with 20 columns:
#'   \describe{
#'     \item{STUDYID}{undocumented field}
#'     \item{DOMAIN}{undocumented field}
#'     \item{USUBJID}{undocumented field}
#'     \item{QSSEQ}{undocumented field}
#'     \item{QSTESTCD}{undocumented field}
#'     \item{QSTEST}{undocumented field}
#'     \item{QSCAT}{undocumented field}
#'     \item{QSSCAT}{undocumented field}
#'     \item{QSORRES}{undocumented field}
#'     \item{QSORRESU}{undocumented field}
#'     \item{QSSTRESC}{undocumented field}
#'     \item{QSSTRESN}{undocumented field}
#'     \item{QSSTRESU}{undocumented field}
#'     \item{QSBLFL}{undocumented field}
#'     \item{QSDRVFL}{undocumented field}
#'     \item{VISITNUM}{undocumented field}
#'     \item{VISIT}{undocumented field}
#'     \item{VISITDY}{undocumented field}
#'     \item{QSDTC}{undocumented field}
#'     \item{QSDY}{undocumented field}
#'   }
#'
#' @source Constructed using qs from the {pharmaversesdtm} package
#' @details Contains a set of 29 unique Test Short Names and Test Names: \tabular{ll}{
#'   \strong{QSTESTCD} \tab \strong{QSTEST} \cr
#'   VFQ101  \tab Your Overall Health Is                    \cr
#'   VFQ102  \tab Eyesight Using Both Eyes Is               \cr
#'   VFQ103  \tab How Often You Worry About Eyesight        \cr
#'   VFQ104  \tab How Often Pain in and Around Eyes         \cr
#'   VFQ105  \tab Difficulty Reading Newspapers             \cr
#'   VFQ106  \tab Difficulty Doing Work/Hobbies             \cr
#'   VFQ107  \tab Difficulty Finding on Crowded Shelf       \cr
#'   VFQ108  \tab Difficulty Reading Street Signs           \cr
#'   VFQ109  \tab Difficulty Going Down Step at Night       \cr
#'   VFQ110  \tab Difficulty Noticing Objects to Side       \cr
#'   VFQ111  \tab Difficulty Seeing How People React        \cr
#'   VFQ112  \tab Difficulty Picking Out Own Clothes        \cr
#'   VFQ113  \tab Difficulty Visiting With People           \cr
#'   VFQ114  \tab Difficulty Going Out to See Movies        \cr
#'   VFQ115  \tab Are You Currently Driving                 \cr
#'   VFQ115C \tab Difficulty Driving During Daytime         \cr
#'   VFQ116  \tab Difficulty Driving at Night               \cr
#'   VFQ116A \tab Driving in Difficult Conditions           \cr
#'   VFQ119  \tab Eye Pain Keep You From Doing What You Like\cr
#'   VFQ120  \tab I Stay Home Most of the Time              \cr
#'   VFQ121  \tab I Feel Frustrated a Lot of the Time       \cr
#'   VFQ124  \tab I Need a Lot of Help From Others          \cr
#'   VFQ125  \tab Worry I'll Do Embarrassing Things         \cr
#'   VFQ1A03 \tab Difficulty Reading Small Print            \cr
#'   VFQ1A04 \tab Difficulty Figure Out Bill Accuracy       \cr
#'   VFQ1A05 \tab Difficulty Shaving or Styling Hair        \cr
#'   VFQ1A06 \tab Difficulty Recognizing People             \cr
#'   VFQ1A07 \tab Difficulty Taking Part in Sports          \cr
#'   VFQ1A08 \tab Difficulty Seeing Programs on TV          
#' }

"qs_ophtha"
