# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Questionnaire for Ophthalmology
#'
#' An example Questionnaires SDTM dataset with ophthalmology-specific questionnaire of NEI VFQ-25
#'
#' @name qs_ophtha
#' @title Questionnaire for Ophthalmology
#' @keywords dataset
#' @description An example Questionnaires SDTM dataset with ophthalmology-specific questionnaire of NEI VFQ-25
#' @docType data
#' @format A data frame with 20 columns:
#'   \describe{
#'     \item{STUDYID}{undocumented field}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{QSSEQ}{Sequence Number}
#'     \item{QSTESTCD}{Question Short Name}
#'     \item{QSTEST}{Question Name}
#'     \item{QSCAT}{Category of Question}
#'     \item{QSSCAT}{Subcategory for Question}
#'     \item{QSORRES}{Finding in Original Units}
#'     \item{QSORRESU}{Original Units}
#'     \item{QSSTRESC}{Character Result/Finding in Std Format}
#'     \item{QSSTRESN}{Numeric Finding in Standard Units}
#'     \item{QSSTRESU}{Standard Units}
#'     \item{QSBLFL}{Baseline Flag}
#'     \item{QSDRVFL}{Derived Flag}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{VISITDY}{Planned Study Day of Visit}
#'     \item{QSDTC}{Date/Time of Finding}
#'     \item{QSDY}{Study Day of Finding}
#'   }
#'
#' @source Constructed using qs from the {pharmaversesdtm} package
"qs_ophtha"
