# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Disease Response (RECIST 1.1) for Oncology
#'
#' A SDTM RS dataset using RECIST 1.1 intended for examples of ADaM dataset creation
#'
#' @name rs_onco_recist
#' @title Disease Response (RECIST 1.1) for Oncology
#' @keywords dataset
#' @description A SDTM RS dataset using RECIST 1.1 intended for examples of ADaM dataset creation
#' @docType data
#' @format A data frame with 14 columns:
#'   \describe{
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{STUDYID}{Study Identifier}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{RSTESTCD}{Assessment Short Name}
#'     \item{RSTEST}{Assessment Name}
#'     \item{RSORRES}{Result or Finding in Original Units}
#'     \item{RSSTRESC}{Character Result/Finding in Std Format}
#'     \item{RSEVAL}{Evaluator}
#'     \item{RSEVALID}{Evaluator Identifier}
#'     \item{RSACPTFL}{Accepted Record Flag}
#'     \item{RSDTC}{Date/Time of Assessment}
#'     \item{RSSEQ}{Sequence Number}
#'   }
#'
#' @source Generated dataset.
#' @author Stefan Bundfuss
#' @details Contains a set of 1 unique Test Short Name and Test Name: \tabular{ll}{
#'   \strong{RSTESTCD} \tab \strong{RSTEST} \cr
#'   OVRLRESP \tab Overall Response
#' }

"rs_onco_recist"
