# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Disease Response (PCWG3) for Oncology
#'
#' A SDTM RS dataset for oncology studies using PCWG3 criteria intended for examples of ADaM dataset creation
#'
#' @name rs_onco_pcwg3
#' @title Disease Response (PCWG3) for Oncology
#' @keywords dataset
#' @description A SDTM RS dataset for oncology studies using PCWG3 criteria intended for examples of ADaM dataset creation
#' @docType data
#' @format A data frame with 14 columns:
#'   \describe{
#'     \item{STUDYID}{undocumented field}
#'     \item{DOMAIN}{undocumented field}
#'     \item{USUBJID}{undocumented field}
#'     \item{RSSEQ}{undocumented field}
#'     \item{RSTESTCD}{undocumented field}
#'     \item{RSTEST}{undocumented field}
#'     \item{RSCAT}{undocumented field}
#'     \item{RSORRES}{undocumented field}
#'     \item{RSSTRESC}{undocumented field}
#'     \item{RSEVAL}{undocumented field}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{undocumented field}
#'     \item{RSDTC}{undocumented field}
#'     \item{RSDY}{Study Day of Specimen Collection}
#'   }
#'
#' @source Generated dataset
#' @author Tomoyuki Namai
"rs_onco_pcwg3"
