# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Disease Response (GCIG)
#'
#' A SDTM RS dataset using GCIG criteria. The dataset contains just a few patients. It is intended for vignettes and examples of ADaM dataset creation.
#'
#' @name rs_onco_ca125
#' @title Disease Response (GCIG)
#' @keywords dataset
#' @description A SDTM RS dataset using GCIG criteria. The dataset contains just a few patients. It is intended for vignettes and examples of ADaM dataset creation.
#' @docType data
#' @format A data frame with 13 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{RSSEQ}{Sequence Number}
#'     \item{RSTESTCD}{Assessment Short Name}
#'     \item{RSTEST}{Assessment Name}
#'     \item{RSCAT}{Category for Assessment}
#'     \item{RSORRES}{Result or Finding in Original Units}
#'     \item{RSSTRESC}{Character Result/Finding in Std Format}
#'     \item{RSEVAL}{Evaluator}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{RSDTC}{Date/Time of Assessment}
#'   }
#'
#' @source Generated dataset ([rs_supprs_onco_ca125.R](https://github.com/pharmaverse/pharmaversesdtm/blob/main/data-raw/rs_supprs_onco_ca125.R))
#' @author Vinh Nguyen
#' @details Contains a set of 1 unique Test Short Name and Test Name: \tabular{ll}{
#'   \strong{RSTESTCD} \tab \strong{RSTEST} \cr
#'   OVRLRESP \tab Overall Response
#' }

"rs_onco_ca125"
