# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Disease Response (Lymphoma Lugano 2014)
#'
#' A SDTM RS domain for lymphoma studies using Lugano 2014 response criteria intended for examples of ADaM dataset creation
#'
#' @name rs_onco_lymphoma
#' @title Disease Response (Lymphoma Lugano 2014)
#' @keywords dataset oncology
#' @description A SDTM RS domain for lymphoma studies using Lugano 2014 response criteria intended for examples of ADaM dataset creation
#' @docType data
#' @format A data frame with 18 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{RSSEQ}{Sequence Number}
#'     \item{RSTESTCD}{Response Assessment Short Name}
#'     \item{RSTEST}{Response Assessment Name}
#'     \item{RSCAT}{Category for Response Assessment}
#'     \item{RSMETHOD}{undocumented field}
#'     \item{RSSCAT}{undocumented field}
#'     \item{RSORRES}{Response Assessment Original Result}
#'     \item{RSSTRESC}{Response Assessment Result in Std Format}
#'     \item{RSSTAT}{Completion Status}
#'     \item{RSEVAL}{Evaluator}
#'     \item{RSLOBXFL}{Last Observation Before Exposure Flag}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{RSDTC}{Date/Time of Response Assessment}
#'     \item{RSDY}{Study Day of Response Assessment}
#'   }
#'
#' @source Generated dataset.
#' @author Kiran Peddamudium
#' @details Contains a set of 1 unique Test Short Name and Test Name: \tabular{ll}{
#'   \strong{RSTESTCD} \tab \strong{RSTEST} \cr
#'   OVRLRESP \tab Overall Response
#' }

"rs_onco_lymphoma"
