# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Disease Response (iRECIST) for Oncology
#'
#' A SDTM RS dataset using iRECIST intended for examples of ADaM dataset creation
#'
#' @name rs_onco_irecist
#' @title Disease Response (iRECIST) for Oncology
#' @keywords dataset
#' @description A SDTM RS dataset using iRECIST intended for examples of ADaM dataset creation
#' @docType data
#' @format A data frame with 19 columns:
#'   \describe{
#'     \item{STUDYID}{undocumented field}
#'     \item{DOMAIN}{undocumented field}
#'     \item{USUBJID}{undocumented field}
#'     \item{RSSEQ}{undocumented field}
#'     \item{RSLNKGRP}{undocumented field}
#'     \item{RSTESTCD}{undocumented field}
#'     \item{RSTEST}{undocumented field}
#'     \item{RSCAT}{undocumented field}
#'     \item{RSORRES}{undocumented field}
#'     \item{RSSTRESC}{undocumented field}
#'     \item{RSSTAT}{undocumented field}
#'     \item{RSREASND}{undocumented field}
#'     \item{RSEVAL}{undocumented field}
#'     \item{RSEVALID}{undocumented field}
#'     \item{RSACPTFL}{undocumented field}
#'     \item{VISITNUM}{undocumented field}
#'     \item{VISIT}{undocumented field}
#'     \item{RSDTC}{undocumented field}
#'     \item{RSDY}{undocumented field}
#'   }
#'
#' @source Generated dataset.
#' @author Rohan Thampi
#' @details Contains a set of 6 unique Test Short Names and Test Names: \tabular{ll}{
#'   \strong{RSTESTCD} \tab \strong{RSTEST} \cr
#'   IRECLIND \tab Last iRECIST Assessment Indicator\cr
#'   NEWLIND  \tab New Lesion Indicator             \cr
#'   NEWLPROG \tab New Lesion Progression           \cr
#'   NTRGRESP \tab Non-target Response              \cr
#'   OVRLRESP \tab Overall Response                 \cr
#'   TRGRESP  \tab Target Response                  
#' }

"rs_onco_irecist"
