# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' No label available
#'
#' No description available
#'
#' @name rs_onco_ca125
#' @title No label available
#' @keywords dataset
#' @description dataset
#' @docType data
#' @format A data frame with 13 columns:
#'   \describe{
#'     \item{STUDYID}{undocumented field}
#'     \item{DOMAIN}{undocumented field}
#'     \item{USUBJID}{undocumented field}
#'     \item{RSSEQ}{undocumented field}
#'     \item{RSTESTCD}{undocumented field}
#'     \item{RSTEST}{undocumented field}
#'     \item{RSCAT}{undocumented field}
#'     \item{RSORRES}{undocumented field}
#'     \item{RSSTRESC}{undocumented field}
#'     \item{RSEVAL}{undocumented field}
#'     \item{VISITNUM}{undocumented field}
#'     \item{VISIT}{undocumented field}
#'     \item{RSDTC}{undocumented field}
#'   }
#'
#' @source No source available
"rs_onco_ca125"
