# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' SDG
#'
#' An example SDG dataset
#'
#' @name sdg_db
#' @title SDG
#' @description An example SDG dataset
#' @docType data
#' @format A data frame with 5 columns:
#'   \describe{
#'     \item{termchar}{undocumented field}
#'     \item{sdg_name}{undocumented field}
#'     \item{sdg_id}{undocumented field}
#'     \item{termvar}{undocumented field}
#'     \item{version}{undocumented field}
#'   }
#'
#' @source <a href="https://github.com/cdisc-org/sdtm-adam-pilot-project/blob/master/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/sv.xpt?raw=true" target="_blank">Access the source of the SDG dataset.</a>
"sdg_db"
