# This file is automatically generated.
# Manual edits are not recommended, as changes may be overwritten.
#' smq_db
#'
#' Standardized MedDRA Queries
#'
#' An example SMQ dataset
#'
#' @name smq_db
#' @docType data
#' @format A data frame with 6 columns:
#'   \describe{
#'     \item{termchar}{undocumented field}
#'     \item{scope}{undocumented field}
#'     \item{smq_name}{undocumented field}
#'     \item{smq_id}{undocumented field}
#'     \item{version}{undocumented field}
#'     \item{termvar}{undocumented field}
#'   }
#'
#' @source Generated dataset.
"smq_db"
