# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Standardized MedDRA Queries
#'
#' An example SMQ dataset
#'
#' @name smq_db
#' @title Standardized MedDRA Queries
#' @keywords dataset
#' @description An example SMQ dataset
#' @docType data
#' @format A data frame with 6 columns:
#'   \describe{
#'     \item{termchar}{undocumented field}
#'     \item{scope}{undocumented field}
#'     \item{smq_name}{undocumented field}
#'     \item{smq_id}{undocumented field}
#'     \item{version}{undocumented field}
#'     \item{termvar}{undocumented field}
#'   }
#'
#' @source Generated dataset.
"smq_db"
