# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Supplemental Qualifiers for Demographics for Vaccine
#'
#' An example SDTM SUPPDM dataset for vaccine studies
#'
#' @name suppdm_vaccine
#' @title Supplemental Qualifiers for Demographics for Vaccine
#' @keywords dataset
#' @description An example SDTM SUPPDM dataset for vaccine studies
#' @docType data
#' @format A data frame with 9 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{RDOMAIN}{Related Domain Abbreviation}
#'     \item{IDVAR}{Identifying Variable}
#'     \item{IDVARVAL}{Identifying Variable Value}
#'     \item{QNAM}{Qualifier Variable Name}
#'     \item{QVAL}{Data Value}
#'     \item{QLABEL}{Qualifier Variable Label}
#'     \item{QORIG}{Origin}
#'   }
#'
#' @source Constructed by {admiralvaccine} developers
"suppdm_vaccine"
