# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' No label available
#'
#' No description available
#'
#' @name supprs_onco_ca125
#' @title No label available
#' @keywords dataset
#' @description dataset
#' @docType data
#' @format A data frame with 9 columns:
#'   \describe{
#'     \item{STUDYID}{undocumented field}
#'     \item{RDOMAIN}{undocumented field}
#'     \item{USUBJID}{undocumented field}
#'     \item{IDVAR}{undocumented field}
#'     \item{IDVARVAL}{undocumented field}
#'     \item{QNAM}{undocumented field}
#'     \item{QLABEL}{undocumented field}
#'     \item{QVAL}{undocumented field}
#'     \item{QORIG}{undocumented field}
#'   }
#'
#' @source No source available
"supprs_onco_ca125"
