# This file is automatically generated. Manual edits are not recommended, as changes may be overwritten.
#' suppdm_vaccine
#'
#' Supplemental Qualifiers for Demographics for Vaccine
#'
#' An example SDTM SUPPDM dataset for vaccine studies
#'
#' @name suppdm_vaccine
#' @docType data
#' @format A data frame with 9 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{RDOMAIN}{Related Domain Abbreviation}
#'     \item{IDVAR}{Identifying Variable}
#'     \item{IDVARVAL}{Identifying Variable Value}
#'     \item{QNAM}{Qualifier Variable Name}
#'     \item{QVAL}{Data Value}
#'     \item{QLABEL}{Qualifier Variable Label}
#'     \item{QORIG}{Origin}
#'   }
#'
#' @source Constructed by {admiralvaccine} developers
"suppdm_vaccine"
