# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Supplemental Qualifiers for RS_ONCO_CA125
#'
#' A SDTM supplemental RS dataset using GCIG criteria. It is intended to be used together with `rs_onco_ca125`.
#'
#' @name supprs_onco_ca125
#' @title Supplemental Qualifiers for RS_ONCO_CA125
#' @keywords dataset
#' @description A SDTM supplemental RS dataset using GCIG criteria. It is intended to be used together with `rs_onco_ca125`.
#' @docType data
#' @format A data frame with 9 columns:
#'   \describe{
#'     \item{STUDYID}{undocumented field}
#'     \item{RDOMAIN}{undocumented field}
#'     \item{USUBJID}{undocumented field}
#'     \item{IDVAR}{undocumented field}
#'     \item{IDVARVAL}{undocumented field}
#'     \item{QNAM}{undocumented field}
#'     \item{QLABEL}{undocumented field}
#'     \item{QVAL}{undocumented field}
#'     \item{QORIG}{undocumented field}
#'   }
#'
#' @source Generated dataset ([rs_supprs_onco_ca125.R](https://github.com/pharmaverse/pharmaversesdtm/blob/main/data-raw/rs_supprs_onco_ca125.R))
#' @author Vinh Nguyen
"supprs_onco_ca125"
