# This file is automatically generated.
# Manual edits are not recommended, as changes may be overwritten.
#' suppds
#'
#' Supplemental Disposition
#'
#' A SDTM SUPPDS dataset from the CDISC pilot project
#'
#' @name suppds
#' @docType data
#' @format A data frame with 9 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{RDOMAIN}{Related Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{IDVAR}{Identifying Variable}
#'     \item{IDVARVAL}{Identifying Variable Value}
#'     \item{QNAM}{Qualifier Variable Name}
#'     \item{QLABEL}{Qualifier Variable Label}
#'     \item{QVAL}{Data Value}
#'     \item{QORIG}{Origin}
#'   }
#'
#' @source https://github.com/cdisc-org/sdtm-adam-pilot-project/blob/master/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/suppdm.xpt?raw=true # nolint
"suppds"
