# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Supplemental Demography
#'
#' A SDTM SUPPDM dataset from the CDISC pilot project
#'
#' @name suppdm
#' @title Supplemental Demography
#' @keywords dataset
#' @description A SDTM SUPPDM dataset from the CDISC pilot project
#' @docType data
#' @format A data frame with 10 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{RDOMAIN}{Related Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{IDVAR}{Identifying Variable}
#'     \item{IDVARVAL}{Identifying Variable Value}
#'     \item{QNAM}{Qualifier Variable Name}
#'     \item{QLABEL}{Qualifier Variable Label}
#'     \item{QVAL}{Data Value}
#'     \item{QORIG}{Origin}
#'     \item{QEVAL}{Evaluator}
#'   }
#'
#' @source Generated dataset.
"suppdm"
