# This file is automatically generated. Manual edits are not recommended, as changes may be overwritten.
#' suppex_vaccine
#'
#' Supplemental Qualifiers for Exposures for Vaccine
#'
#' An example SDTM SUPPEX dataset for vaccine studies
#'
#' @name suppex_vaccine
#' @docType data
#' @format A data frame with 9 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{RDOMAIN}{Related Domain Abbreviation}
#'     \item{IDVAR}{Identifying Variable}
#'     \item{IDVARVAL}{Identifying Variable Value}
#'     \item{QNAM}{Qualifier Variable Name}
#'     \item{QVAL}{Data Value}
#'     \item{QLABEL}{Qualifier Variable Label}
#'     \item{QORIG}{Origin}
#'   }
#'
#' @source Constructed by {admiralvaccine} developers
"suppex_vaccine"
