# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Supplemental Qualifiers for RS_ONCO_IMWG
#'
#' A SDTM supplemental RS dataset using IMWG criteria intended to be used with `rs_onco_imwg`
#'
#' @name supprs_onco_imwg
#' @title Supplemental Qualifiers for RS_ONCO_IMWG
#' @keywords dataset
#' @description A SDTM supplemental RS dataset using IMWG criteria intended to be used with `rs_onco_imwg`
#' @docType data
#' @format A data frame with 9 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{RDOMAIN}{Related Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{IDVAR}{Identifying Variable}
#'     \item{IDVARVAL}{Identifying Variable Value}
#'     \item{QNAM}{Qualifier Variable Name}
#'     \item{QLABEL}{Qualifier Variable Label}
#'     \item{QVAL}{Data Value}
#'     \item{QORIG}{Origin}
#'   }
#'
#' @source [Access the source of the Supplemental Qualifiers for RS_ONCO_IMWG dataset.](https://github.com/cdisc-org/sdtm-adam-pilot-project/blob/master/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/suppae.xpt?raw=true)
#' @author Vinh Nguyen
"supprs_onco_imwg"
