# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Subject Visits
#'
#' A SDTM SV dataset from the CDISC pilot project with corrected duplicate observation
#'
#' @name sv
#' @title Subject Visits
#' @keywords dataset
#' @description A SDTM SV dataset from the CDISC pilot project with corrected duplicate observation
#' @docType data
#' @format A data frame with 8 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{VISITDY}{Planned Study Day of Visit}
#'     \item{SVSTDTC}{Start Date/Time of Visit}
#'     \item{SVENDTC}{End Date/Time of Visit}
#'   }
#'
#' @source Constructed by {admiralvaccine} developers
"sv"
