# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Tumor Results (RECIST 1.1) for Oncology
#'
#' A SDTM TR dataset using RECIST 1.1 intended for examples of ADaM dataset creation
#'
#' @name tr_onco_recist
#' @title Tumor Results (RECIST 1.1) for Oncology
#' @description A SDTM TR dataset using RECIST 1.1 intended for examples of ADaM dataset creation
#' @docType data
#' @format A data frame with 21 columns:
#'   \describe{
#'     \item{TRLNKID}{undocumented field}
#'     \item{TRTESTCD}{undocumented field}
#'     \item{TRORRES}{undocumented field}
#'     \item{VISITNUM}{undocumented field}
#'     \item{TREVALID}{undocumented field}
#'     \item{TRGRPID}{undocumented field}
#'     \item{.before}{undocumented field}
#'     \item{TREVAL}{undocumented field}
#'     \item{TRACPTFL}{undocumented field}
#'     \item{.after}{undocumented field}
#'     \item{USUBJID}{undocumented field}
#'     \item{TRDTC}{undocumented field}
#'     \item{DOMAIN}{undocumented field}
#'     \item{STUDYID}{undocumented field}
#'     \item{TRTEST}{undocumented field}
#'     \item{VISIT}{undocumented field}
#'     \item{TRORRESU}{undocumented field}
#'     \item{TRSTRESC}{undocumented field}
#'     \item{TRSTRESN}{undocumented field}
#'     \item{TRSTRESU}{undocumented field}
#'     \item{TRSEQ}{undocumented field}
#'   }
#'
#' @source Source: Generated dataset.
#' @author Stefan Bundfuss
"tr_onco_recist"
