# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Tumor Results (RECIST 1.1) for Oncology
#'
#' A SDTM TR dataset using RECIST 1.1 intended for examples of ADaM dataset creation
#'
#' @name tr_onco_recist
#' @title Tumor Results (RECIST 1.1) for Oncology
#' @keywords dataset
#' @description A SDTM TR dataset using RECIST 1.1 intended for examples of ADaM dataset creation
#' @docType data
#' @format A data frame with 19 columns:
#'   \describe{
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{STUDYID}{Study Identifier}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{TRGRPID}{Group ID}
#'     \item{TRLNKID}{Link ID}
#'     \item{TRTESTCD}{Tumor/Lesion Assessment Short Name}
#'     \item{TRTEST}{Tumor/Lesion Assessment Test Name}
#'     \item{TRORRES}{Result or Finding in Original Units}
#'     \item{TRORRESU}{Original Units}
#'     \item{TRSTRESC}{Character Result/Finding in Std Format}
#'     \item{TRSTRESN}{Numeric Result/Finding in Standard Units}
#'     \item{TRSTRESU}{Standard Units}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{TREVAL}{Evaluator}
#'     \item{TREVALID}{Evaluator Identifier}
#'     \item{TRACPTFL}{Accepted Record Flag}
#'     \item{TRDTC}{Date/Time of Tumor/Lesion Measurement}
#'     \item{TRSEQ}{Sequence Number}
#'   }
#'
#' @source Generated dataset.
#' @author Stefan Bundfuss
#' @details Contains a set of 3 unique Test Short Names and Test Names: \tabular{ll}{
#'   \strong{TRTESTCD} \tab \strong{TRTEST} \cr
#'   LDIAM    \tab Longest Diameter     \cr
#'   LPERP    \tab Longest Perpendicular\cr
#'   TUMSTATE \tab Tumor State
#' }

"tr_onco_recist"
