# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Trial Design
#'
#' A SDTM TS dataset from the CDISC pilot project
#'
#' @name ts
#' @title Trial Design
#' @keywords dataset
#' @description A SDTM TS dataset from the CDISC pilot project
#' @docType data
#' @format A data frame with 6 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{TSSEQ}{Sequence Number}
#'     \item{TSPARMCD}{Trial Summary Parameter Short Name}
#'     \item{TSPARM}{Trial Summary Parameter}
#'     \item{TSVAL}{Parameter Value}
#'   }
#'
#' @source [Access the source of the Trial Design dataset.](https://github.com/cdisc-org/sdtm-adam-pilot-project/blob/master/updated-pilot-submission-package/900172/m5/datasets/cdiscpilot01/tabulations/sdtm/vs.xpt?raw=true)
"ts"
