# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Tumor Identification for Oncology
#'
#' A SDTM TU dataset simulated by Gopi Vegesna
#'
#' @name tu_onco
#' @title Tumor Identification for Oncology
#' @keywords dataset
#' @description A SDTM TU dataset simulated by Gopi Vegesna
#' @docType data
#' @format A data frame with 18 columns:
#'   \describe{
#'     \item{STUDYID}{Study Identifier}
#'     \item{DOMAIN}{Domain Abbreviation}
#'     \item{USUBJID}{Unique Subject Identifier}
#'     \item{TUSEQ}{Sequence Number}
#'     \item{TULNKID}{Link ID}
#'     \item{TUTESTCD}{Tumor Identification Short Name}
#'     \item{TUTEST}{Tumor Identification Test Name}
#'     \item{TUORRES}{Tumor Identification Result}
#'     \item{TUSTRESC}{Tumor Identification Result Std. Format}
#'     \item{TULOC}{Location of the Tumor}
#'     \item{TUMETHOD}{Method of Identification}
#'     \item{TUEVAL}{Evaluator}
#'     \item{TUEVALID}{Evaluator Identifier}
#'     \item{TUACPTFL}{Accepted Record Flag}
#'     \item{VISITNUM}{Visit Number}
#'     \item{VISIT}{Visit Name}
#'     \item{TUDTC}{Date/Time of Tumor Identification}
#'     \item{TUDY}{Study Day of Tumor Identification}
#'   }
#'
#' @source Generated dataset.
#' @author Gopi Vegesna
#' @details Contains a set of 1 unique Test Short Name and Test Name: \tabular{ll}{
#'   \strong{TUTESTCD} \tab \strong{TUTEST} \cr
#'   TUMIDENT \tab Tumor Identification
#' }

"tu_onco"
