# This file is automatically generated by data-raw/create_sdtms_data.R.
# For updating it please edit inst/extdata/sdtms-specs.json and rerun create_sdtms_data.R.
# Manual edits are not recommended, as changes may be overwritten.
#' Tumor Identification (RECIST 1.1) for Oncology
#'
#' A SDTM TU dataset using RECIST 1.1 intended for examples of ADaM dataset creation
#'
#' @name tu_onco_recist
#' @title Tumor Identification (RECIST 1.1) for Oncology
#' @keywords dataset
#' @description A SDTM TU dataset using RECIST 1.1 intended for examples of ADaM dataset creation
#' @docType data
#' @format A data frame with 16 columns:
#'   \describe{
#'     \item{DOMAIN}{undocumented field}
#'     \item{STUDYID}{undocumented field}
#'     \item{USUBJID}{undocumented field}
#'     \item{VISIT}{undocumented field}
#'     \item{VISITNUM}{undocumented field}
#'     \item{TULOC}{undocumented field}
#'     \item{TUTESTCD}{undocumented field}
#'     \item{TUTEST}{undocumented field}
#'     \item{TUORRES}{undocumented field}
#'     \item{TUSTRESC}{undocumented field}
#'     \item{TUMETHOD}{undocumented field}
#'     \item{TULNKID}{undocumented field}
#'     \item{TUEVAL}{undocumented field}
#'     \item{TUEVALID}{undocumented field}
#'     \item{TUACPTFL}{undocumented field}
#'     \item{TUSEQ}{undocumented field}
#'   }
#'
#' @source Generated dataset.
#' @author Stefan Bundfuss
"tu_onco_recist"
